"""CERR Mahalla Analytics v2 — read-only data layer.

CERR_DATA_ROOT may be either:
  - A local filesystem path (e.g. /data/cerr_runs or the in-repo default), OR
  - An HTTP(S) URL pointing at a static-asset host such as Cloudflare R2
    (e.g. https://cerr-data.devgokal.com).

In HTTP mode we require a manifest.json at the root listing the region
directories — R2 (and any plain S3-style bucket exposed over HTTP) does not
expose key listings, so we can't discover regions by walking. The manifest
is generated by `python -m app.scripts.build_cerr_manifest` against a local
copy before upload.

In FS mode the manifest is optional; if absent we scan the directory.

Coordinates stay in WGS84 (lon/lat) — MapLibre GL consumes them natively.
"""
from __future__ import annotations

import json
import threading
from pathlib import Path
from typing import Any

from ..config import get_settings


# ----------------------------------------------------------------------
# Reader: abstracts "read JSON at relative path X under the root", with
# in-process cache so each remote file is fetched at most once.
# ----------------------------------------------------------------------

class _Reader:
    def __init__(self, root: str):
        self._is_http = root.startswith("http://") or root.startswith("https://")
        self._root = root.rstrip("/")
        self._cache: dict[str, Any] = {}
        self._cache_lock = threading.Lock()
        self._client = None
        if self._is_http:
            # Local import keeps httpx optional in pure-fs deployments.
            import httpx
            self._client = httpx.Client(timeout=30.0, follow_redirects=True)

    @property
    def is_http(self) -> bool:
        return self._is_http

    @property
    def root(self) -> str:
        return self._root

    def read_json(self, rel: str) -> Any:
        rel = rel.lstrip("/")
        with self._cache_lock:
            if rel in self._cache:
                return self._cache[rel]
        data = self._fetch(rel)
        with self._cache_lock:
            self._cache[rel] = data
        return data

    def _fetch(self, rel: str) -> Any:
        if self._is_http:
            url = f"{self._root}/{rel}"
            try:
                r = self._client.get(url)
                if r.status_code == 404:
                    return None
                r.raise_for_status()
                return r.json()
            except Exception:
                return None
        p = Path(self._root) / rel
        if not p.exists():
            return None
        try:
            return json.loads(p.read_text(encoding="utf-8"))
        except Exception:
            return None

    def list_region_dirs(self) -> list[tuple[int, str]]:
        """Returns [(region_code, region_dir_name), ...]. Prefers manifest.json,
        falls back to filesystem scan when running on local disk."""
        manifest = self.read_json("manifest.json")
        if manifest:
            out: list[tuple[int, str]] = []
            for r in manifest.get("regions", []):
                try:
                    out.append((int(r["code"]), r["dir"]))
                except (KeyError, ValueError, TypeError):
                    continue
            return out
        if self._is_http:
            # No manifest in HTTP mode = nothing we can do.
            return []
        root = Path(self._root)
        if not root.exists():
            return []
        out = []
        for d in sorted(root.iterdir()):
            if not d.is_dir():
                continue
            code_str = d.name.split("_", 1)[0]
            if code_str.isdigit():
                out.append((int(code_str), d.name))
        return out


# ----------------------------------------------------------------------
# Index — keyed by region/district code, stores rel_dir strings rather than
# Path objects so reads work uniformly in both FS and HTTP modes.
# ----------------------------------------------------------------------

class CerrDataIndex:
    def __init__(self, root: str):
        self._reader = _Reader(root)
        self._lock = threading.Lock()
        self._loaded = False
        self.regions: dict[int, dict[str, Any]] = {}
        self.regions_ordered: list[dict[str, Any]] = []
        self.districts: dict[int, dict[str, Any]] = {}
        self.region_districts: dict[int, list[dict[str, Any]]] = {}

    def _ensure_loaded(self) -> None:
        if self._loaded:
            return
        with self._lock:
            if self._loaded:
                return
            self._scan()
            self._loaded = True

    def _scan(self) -> None:
        for code, dir_name in self._reader.list_region_dirs():
            summary = self._reader.read_json(f"{dir_name}/summary.json")
            if not summary:
                continue
            region = self._reader.read_json(f"{dir_name}/region.json")
            mahalla_count = sum(d.get("mahalla_count", 0) for d in summary.get("districts", []))
            if region:
                mahalla_count = region.get("region_mahalla_count", mahalla_count)
            self.regions[code] = {
                "code": code,
                "name": summary["region_name"],
                "mahalla_count": mahalla_count,
                "districts_count": len(summary.get("districts", [])),
                "rel_dir": dir_name,
            }

            district_list: list[dict[str, Any]] = []
            for d in summary.get("districts", []):
                dcode = int(d["code"])
                slug = d["slug"]
                drec = {
                    "code": dcode,
                    "name": d["name"],
                    "region_code": code,
                    "region_name": summary["region_name"],
                    "mahalla_count": d.get("mahalla_count", 0),
                    "has_macro": d.get("has_macro", False),
                    "has_geo": d.get("has_geo", False),
                    "rel_dir": f"{dir_name}/districts/{dcode}_{slug}",
                }
                self.districts[dcode] = drec
                district_list.append({k: v for k, v in drec.items() if k != "rel_dir"})
            self.region_districts[code] = district_list

        self.regions_ordered = sorted(
            ({k: v for k, v in r.items() if k != "rel_dir"} for r in self.regions.values()),
            key=lambda r: r["name"],
        )

    # ------------------------------------------------------------------
    # Public read API
    # ------------------------------------------------------------------

    def list_regions(self) -> list[dict[str, Any]]:
        self._ensure_loaded()
        return self.regions_ordered

    def get_region(self, region_code: int) -> dict[str, Any] | None:
        self._ensure_loaded()
        r = self.regions.get(region_code)
        if not r:
            return None
        return {k: v for k, v in r.items() if k != "rel_dir"}

    def get_region_overview(self, region_code: int) -> dict[str, Any] | None:
        self._ensure_loaded()
        r = self.regions.get(region_code)
        if not r:
            return None
        data = self._reader.read_json(f"{r['rel_dir']}/region.json")
        return (data or {}).get("overview") or {}

    def list_region_districts(self, region_code: int) -> list[dict[str, Any]]:
        self._ensure_loaded()
        return self.region_districts.get(region_code, [])

    def get_district(self, district_code: int) -> dict[str, Any] | None:
        self._ensure_loaded()
        d = self.districts.get(district_code)
        if not d:
            return None
        return {k: v for k, v in d.items() if k != "rel_dir"}

    def get_district_overview(self, district_code: int) -> dict[str, Any] | None:
        self._ensure_loaded()
        d = self.districts.get(district_code)
        if not d:
            return None
        data = self._reader.read_json(f"{d['rel_dir']}/district.json")
        return (data or {}).get("overview") or {}

    def get_district_macro(self, district_code: int) -> dict[str, Any] | None:
        self._ensure_loaded()
        d = self.districts.get(district_code)
        if not d:
            return None
        data = self._reader.read_json(f"{d['rel_dir']}/district.json")
        return (data or {}).get("macro")

    def get_district_geo(self, district_code: int) -> dict[str, Any] | None:
        """Returns raw GeoJSON FeatureCollection in WGS84 (lon/lat)."""
        self._ensure_loaded()
        d = self.districts.get(district_code)
        if not d:
            return None
        return self._reader.read_json(f"{d['rel_dir']}/geo.geojson")

    def list_district_mahallas(
        self, district_code: int, sort: str = "rating_asc", limit: int = 500
    ) -> list[dict[str, Any]]:
        self._ensure_loaded()
        d = self.districts.get(district_code)
        if not d:
            return []
        sums = self._district_mahalla_summaries(d)
        if sort == "rating_desc":
            arr = sorted(sums, key=lambda x: (x.get("rating_score") is None, -(x.get("rating_score") or 0)))
        else:
            arr = sorted(sums, key=lambda x: (x.get("rating_score") is None, x.get("rating_score") or 0))
        return arr[:limit]

    def search_mahallas(self, q: str, limit: int = 100) -> list[dict[str, Any]]:
        self._ensure_loaded()
        ql = q.casefold().strip()
        if not ql:
            return []
        hits: list[dict[str, Any]] = []
        for d in self.districts.values():
            for m in self._district_mahalla_summaries(d):
                name = (m.get("name") or "").casefold()
                stir = m.get("stir") or ""
                if ql in name or stir.startswith(q):
                    hits.append(m)
                    if len(hits) >= limit:
                        return hits
        return hits

    def get_mahalla_overview(self, stir: str) -> dict[str, Any] | None:
        return self._mahalla_overview_lookup(stir)

    def get_mahalla_ai_insights(self, stir: str) -> dict[str, Any] | None:
        ov = self._mahalla_overview_lookup(stir)
        if ov is None:
            return None
        return ov.get("ai_insights")

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _district_mahalla_summaries(self, d: dict[str, Any]) -> list[dict[str, Any]]:
        """Pulls a district's mahallas.json (cached by the reader) and projects
        a summary record per mahalla."""
        data = self._reader.read_json(f"{d['rel_dir']}/mahallas.json")
        if not data:
            return []
        out: list[dict[str, Any]] = []
        for m in data.get("mahallas", []):
            stir = str(m.get("stir") or "")
            if not stir:
                continue
            out.append({
                "stir": stir,
                "name": m.get("name"),
                "district_name": d["name"],
                "region_name": d["region_name"],
                "district_oktmo": d["code"],
                "region_oktmo": d["region_code"],
                "rating_score": m.get("rating_score"),
            })
        return out

    def _mahalla_overview_lookup(self, stir: str) -> dict[str, Any] | None:
        """Walks districts to find a mahalla by STIR. Each district's mahallas.json
        is fetched at most once thanks to the reader cache, so subsequent lookups
        for any STIR are O(districts) but fast (memory-only)."""
        self._ensure_loaded()
        for d in self.districts.values():
            data = self._reader.read_json(f"{d['rel_dir']}/mahallas.json")
            if not data:
                continue
            for m in data.get("mahallas", []):
                if str(m.get("stir") or "") != stir:
                    continue
                ov = m.get("overview")
                if ov is None:
                    return None
                if "ai_insights" not in ov and m.get("ai_insights") is not None:
                    ov = dict(ov)
                    ov["ai_insights"] = m["ai_insights"]
                return ov
        return None


# ----------------------------------------------------------------------
# Singleton accessor
# ----------------------------------------------------------------------

_singleton: CerrDataIndex | None = None
_singleton_lock = threading.Lock()


def get_cerr_index() -> CerrDataIndex:
    global _singleton
    if _singleton is not None:
        return _singleton
    with _singleton_lock:
        if _singleton is None:
            _singleton = CerrDataIndex(get_settings().cerr_data_root_resolved)
    return _singleton
