"""baseline schema

Revision ID: 770ec9ae0fcc
Revises: 
Create Date: 2026-05-10 03:13:17.000253
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '770ec9ae0fcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('import_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_dir', sa.Text(), nullable=False),
    sa.Column('source_file_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed', 'aborted')", name=op.f('ck_import_runs_status_allowed')),
    sa.PrimaryKeyConstraint('import_run_id', name=op.f('pk_import_runs'))
    )
    op.create_table('data_quality_issues',
    sa.Column('issue_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('issue_code', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.Column('mahalla_stir', sa.String(length=32), nullable=True),
    sa.Column('source_json_path', sa.Text(), nullable=True),
    sa.Column('details_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.CheckConstraint("severity IN ('critical', 'warning', 'info')", name=op.f('ck_data_quality_issues_severity_allowed')),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_data_quality_issues_import_run_id_import_runs')),
    sa.PrimaryKeyConstraint('issue_id', name=op.f('pk_data_quality_issues'))
    )
    op.create_index('ix_data_quality_issues_district_code', 'data_quality_issues', ['district_code'], unique=False)
    op.create_index('ix_data_quality_issues_import_run_id', 'data_quality_issues', ['import_run_id'], unique=False)
    op.create_index('ix_data_quality_issues_issue_code', 'data_quality_issues', ['issue_code'], unique=False)
    op.create_index('ix_data_quality_issues_mahalla_stir', 'data_quality_issues', ['mahalla_stir'], unique=False)
    op.create_index('ix_data_quality_issues_region_code', 'data_quality_issues', ['region_code'], unique=False)
    op.create_table('regions',
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('source_region_index', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('region_name_cyr', sa.Text(), nullable=True),
    sa.Column('declared_district_count', sa.Integer(), nullable=True),
    sa.Column('declared_mahalla_count', sa.Integer(), nullable=True),
    sa.Column('actual_district_count', sa.Integer(), nullable=True),
    sa.Column('actual_mahalla_count', sa.Integer(), nullable=True),
    sa.Column('source_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_header_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_overview_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_regions_import_run_id_import_runs')),
    sa.PrimaryKeyConstraint('region_id', name=op.f('pk_regions')),
    sa.UniqueConstraint('import_run_id', 'source_file', 'source_region_index', name='uq_region_lineage')
    )
    op.create_index('ix_regions_import_run_id', 'regions', ['import_run_id'], unique=False)
    op.create_index('ix_regions_region_code', 'regions', ['region_code'], unique=False)
    op.create_table('source_region_files',
    sa.Column('source_file_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('region_code_from_filename', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_source_region_files_import_run_id_import_runs')),
    sa.PrimaryKeyConstraint('source_file_id', name=op.f('pk_source_region_files')),
    sa.UniqueConstraint('import_run_id', 'source_file', name='uq_run_file')
    )
    op.create_index('ix_source_region_files_import_run_id', 'source_region_files', ['import_run_id'], unique=False)
    op.create_index('ix_source_region_files_region_code_from_filename', 'source_region_files', ['region_code_from_filename'], unique=False)
    op.create_table('districts',
    sa.Column('district_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('source_district_index', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.Column('district_name_cyr', sa.Text(), nullable=True),
    sa.Column('declared_mahalla_count', sa.Integer(), nullable=True),
    sa.Column('actual_mahalla_count', sa.Integer(), nullable=True),
    sa.Column('macro_period_label_cyr', sa.Text(), nullable=True),
    sa.Column('raw_overview_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_macro_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_districts_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk_districts_region_id_regions')),
    sa.PrimaryKeyConstraint('district_id', name=op.f('pk_districts')),
    sa.UniqueConstraint('import_run_id', 'source_file', 'source_district_index', name='uq_district_lineage')
    )
    op.create_index('ix_districts_district_code', 'districts', ['district_code'], unique=False)
    op.create_index('ix_districts_import_run_id', 'districts', ['import_run_id'], unique=False)
    op.create_index('ix_districts_region_code', 'districts', ['region_code'], unique=False)
    op.create_index('ix_districts_region_id', 'districts', ['region_id'], unique=False)
    op.create_table('region_geometries',
    sa.Column('region_geometry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('region_geometry_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_region_geometries_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk_region_geometries_region_id_regions')),
    sa.PrimaryKeyConstraint('region_geometry_id', name=op.f('pk_region_geometries'))
    )
    op.create_index('ix_region_geometries_import_run_id', 'region_geometries', ['import_run_id'], unique=False)
    op.create_index('ix_region_geometries_region_id', 'region_geometries', ['region_id'], unique=False)
    op.create_table('district_geometries',
    sa.Column('district_geometry_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('district_geometry_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], name=op.f('fk_district_geometries_district_id_districts')),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_district_geometries_import_run_id_import_runs')),
    sa.PrimaryKeyConstraint('district_geometry_id', name=op.f('pk_district_geometries'))
    )
    op.create_index('ix_district_geometries_district_id', 'district_geometries', ['district_id'], unique=False)
    op.create_index('ix_district_geometries_import_run_id', 'district_geometries', ['import_run_id'], unique=False)
    op.create_table('district_macro_indicators',
    sa.Column('macro_indicator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('indicator_key', sa.String(length=64), nullable=False),
    sa.Column('indicator_label_cyr', sa.Text(), nullable=True),
    sa.Column('indicator_unit', sa.String(length=64), nullable=True),
    sa.Column('indicator_direction', sa.String(length=8), nullable=True),
    sa.Column('period_label_cyr', sa.Text(), nullable=True),
    sa.Column('highlighted_value_num', sa.Float(), nullable=True),
    sa.Column('highlighted_missing_flag', sa.Boolean(), nullable=False),
    sa.Column('highlighted_value_null_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], name=op.f('fk_district_macro_indicators_district_id_districts')),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_district_macro_indicators_import_run_id_import_runs')),
    sa.PrimaryKeyConstraint('macro_indicator_id', name=op.f('pk_district_macro_indicators'))
    )
    op.create_index('ix_district_macro_indicators_district_id', 'district_macro_indicators', ['district_id'], unique=False)
    op.create_index('ix_district_macro_indicators_import_run_id', 'district_macro_indicators', ['import_run_id'], unique=False)
    op.create_index('ix_district_macro_indicators_indicator_key', 'district_macro_indicators', ['indicator_key'], unique=False)
    op.create_table('district_rating_histogram',
    sa.Column('histogram_row_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('bucket_order', sa.Integer(), nullable=False),
    sa.Column('rating_bucket_label_cyr', sa.Text(), nullable=True),
    sa.Column('mahalla_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], name=op.f('fk_district_rating_histogram_district_id_districts')),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_district_rating_histogram_import_run_id_import_runs')),
    sa.PrimaryKeyConstraint('histogram_row_id', name=op.f('pk_district_rating_histogram'))
    )
    op.create_index('ix_district_rating_histogram_district_id', 'district_rating_histogram', ['district_id'], unique=False)
    op.create_index('ix_district_rating_histogram_import_run_id', 'district_rating_histogram', ['import_run_id'], unique=False)
    op.create_table('mahallas',
    sa.Column('mahalla_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('source_district_index', sa.Integer(), nullable=False),
    sa.Column('source_mahalla_index', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.Integer(), nullable=True),
    sa.Column('district_code', sa.Integer(), nullable=True),
    sa.Column('mahalla_stir', sa.String(length=32), nullable=True),
    sa.Column('mahalla_name_cyr', sa.Text(), nullable=True),
    sa.Column('rating_score', sa.Float(), nullable=True),
    sa.Column('district_rank_text', sa.String(length=32), nullable=True),
    sa.Column('region_rank_text', sa.String(length=32), nullable=True),
    sa.Column('category_label_cyr', sa.Text(), nullable=True),
    sa.Column('status_label_cyr', sa.Text(), nullable=True),
    sa.Column('specialization_residual_percent', sa.Float(), nullable=True),
    sa.Column('specialization_total_known_percent', sa.Float(), nullable=True),
    sa.Column('crop_total_homestead_area_sotkah', sa.Float(), nullable=True),
    sa.Column('peer_set_count', sa.Integer(), nullable=True),
    sa.Column('peer_set_description_cyr', sa.Text(), nullable=True),
    sa.Column('peer_fallback_to_district_flag', sa.Boolean(), nullable=True),
    sa.Column('peer_indicator_count', sa.Integer(), nullable=True),
    sa.Column('peer_total_indicators_considered', sa.Integer(), nullable=True),
    sa.Column('raw_header_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('raw_overview_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], name=op.f('fk_mahallas_district_id_districts')),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_mahallas_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk_mahallas_region_id_regions')),
    sa.PrimaryKeyConstraint('mahalla_id', name=op.f('pk_mahallas')),
    sa.UniqueConstraint('import_run_id', 'source_file', 'source_district_index', 'source_mahalla_index', name='uq_mahalla_lineage')
    )
    op.create_index('ix_mahallas_district_code', 'mahallas', ['district_code'], unique=False)
    op.create_index('ix_mahallas_district_id', 'mahallas', ['district_id'], unique=False)
    op.create_index('ix_mahallas_import_run_id', 'mahallas', ['import_run_id'], unique=False)
    op.create_index('ix_mahallas_mahalla_stir', 'mahallas', ['mahalla_stir'], unique=False)
    op.create_index('ix_mahallas_region_code', 'mahallas', ['region_code'], unique=False)
    op.create_index('ix_mahallas_region_id', 'mahallas', ['region_id'], unique=False)
    op.create_table('district_macro_points',
    sa.Column('macro_point_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('macro_indicator_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('point_order', sa.Integer(), nullable=False),
    sa.Column('point_district_name_cyr', sa.Text(), nullable=True),
    sa.Column('point_value_num', sa.Float(), nullable=True),
    sa.Column('is_highlighted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_district_macro_points_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['macro_indicator_id'], ['district_macro_indicators.macro_indicator_id'], name=op.f('fk_district_macro_points_macro_indicator_id_district_macro_indicators')),
    sa.PrimaryKeyConstraint('macro_point_id', name=op.f('pk_district_macro_points'))
    )
    op.create_index('ix_district_macro_points_import_run_id', 'district_macro_points', ['import_run_id'], unique=False)
    op.create_index('ix_district_macro_points_macro_indicator_id', 'district_macro_points', ['macro_indicator_id'], unique=False)
    op.create_table('entity_ai_insights',
    sa.Column('insight_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('mahalla_id', sa.BigInteger(), nullable=True),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('polarity', sa.String(length=8), nullable=False),
    sa.Column('bullet_order', sa.Integer(), nullable=False),
    sa.Column('bullet_text', sa.Text(), nullable=True),
    sa.Column('ai_model_name', sa.Text(), nullable=True),
    sa.Column('ai_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_insights_status', sa.String(length=32), nullable=True),
    sa.CheckConstraint("polarity IN ('pro', 'con')", name=op.f('ck_entity_ai_insights_ai_polarity_allowed')),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], name=op.f('fk_entity_ai_insights_district_id_districts')),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_entity_ai_insights_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.mahalla_id'], name=op.f('fk_entity_ai_insights_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk_entity_ai_insights_region_id_regions')),
    sa.PrimaryKeyConstraint('insight_id', name=op.f('pk_entity_ai_insights'))
    )
    op.create_index('ix_entity_ai_insights_district_id', 'entity_ai_insights', ['district_id'], unique=False)
    op.create_index('ix_entity_ai_insights_import_run_id', 'entity_ai_insights', ['import_run_id'], unique=False)
    op.create_index('ix_entity_ai_insights_mahalla_id', 'entity_ai_insights', ['mahalla_id'], unique=False)
    op.create_index('ix_entity_ai_insights_region_id', 'entity_ai_insights', ['region_id'], unique=False)
    op.create_table('entity_kpis',
    sa.Column('entity_kpi_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_level', sa.String(length=16), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=True),
    sa.Column('district_id', sa.BigInteger(), nullable=True),
    sa.Column('mahalla_id', sa.BigInteger(), nullable=True),
    sa.Column('kpi_key', sa.String(length=64), nullable=False),
    sa.Column('kpi_label_cyr', sa.Text(), nullable=True),
    sa.Column('source_table_name', sa.Text(), nullable=True),
    sa.Column('source_column_name', sa.Text(), nullable=True),
    sa.Column('kpi_format', sa.String(length=32), nullable=True),
    sa.Column('kpi_provenance', sa.String(length=32), nullable=True),
    sa.Column('kpi_direction', sa.String(length=8), nullable=True),
    sa.Column('kpi_value_num', sa.Float(), nullable=True),
    sa.Column('kpi_error_text', sa.Text(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('district_average_value', sa.Float(), nullable=True),
    sa.Column('compare_scope', sa.String(length=32), nullable=True),
    sa.CheckConstraint("entity_level IN ('region', 'district', 'mahalla')", name=op.f('ck_entity_kpis_entity_level_allowed')),
    sa.ForeignKeyConstraint(['district_id'], ['districts.district_id'], name=op.f('fk_entity_kpis_district_id_districts')),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_entity_kpis_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.mahalla_id'], name=op.f('fk_entity_kpis_mahalla_id_mahallas')),
    sa.ForeignKeyConstraint(['region_id'], ['regions.region_id'], name=op.f('fk_entity_kpis_region_id_regions')),
    sa.PrimaryKeyConstraint('entity_kpi_id', name=op.f('pk_entity_kpis'))
    )
    op.create_index('ix_entity_kpis_district_id', 'entity_kpis', ['district_id'], unique=False)
    op.create_index('ix_entity_kpis_entity_level_kpi_key', 'entity_kpis', ['entity_level', 'kpi_key'], unique=False)
    op.create_index('ix_entity_kpis_import_run_id', 'entity_kpis', ['import_run_id'], unique=False)
    op.create_index('ix_entity_kpis_kpi_key', 'entity_kpis', ['kpi_key'], unique=False)
    op.create_index('ix_entity_kpis_mahalla_id', 'entity_kpis', ['mahalla_id'], unique=False)
    op.create_index('ix_entity_kpis_region_id', 'entity_kpis', ['region_id'], unique=False)
    op.create_table('mahalla_appeals',
    sa.Column('appeal_row_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('mahalla_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('crime_appeal_count', sa.Integer(), nullable=True),
    sa.Column('divorce_appeal_count', sa.Integer(), nullable=True),
    sa.Column('social_aid_appeal_count', sa.Integer(), nullable=True),
    sa.Column('employment_appeal_count', sa.Integer(), nullable=True),
    sa.Column('gas_appeal_count', sa.Integer(), nullable=True),
    sa.Column('registry_appeal_count', sa.Integer(), nullable=True),
    sa.Column('appeals_year', sa.Integer(), nullable=True),
    sa.Column('appeals_period_label_cyr', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_mahalla_appeals_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.mahalla_id'], name=op.f('fk_mahalla_appeals_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('appeal_row_id', name=op.f('pk_mahalla_appeals'))
    )
    op.create_index('ix_mahalla_appeals_import_run_id', 'mahalla_appeals', ['import_run_id'], unique=False)
    op.create_index('ix_mahalla_appeals_mahalla_id', 'mahalla_appeals', ['mahalla_id'], unique=False)
    op.create_table('mahalla_crops',
    sa.Column('crop_season_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('mahalla_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('season_order', sa.Integer(), nullable=False),
    sa.Column('season_key', sa.String(length=32), nullable=True),
    sa.Column('season_label_cyr', sa.Text(), nullable=True),
    sa.Column('crops_text_cyr', sa.Text(), nullable=True),
    sa.Column('total_area_ha', sa.Float(), nullable=True),
    sa.Column('homestead_area_ha', sa.Float(), nullable=True),
    sa.Column('household_count', sa.Integer(), nullable=True),
    sa.Column('raw_crops_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_mahalla_crops_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.mahalla_id'], name=op.f('fk_mahalla_crops_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('crop_season_id', name=op.f('pk_mahalla_crops'))
    )
    op.create_index('ix_mahalla_crops_import_run_id', 'mahalla_crops', ['import_run_id'], unique=False)
    op.create_index('ix_mahalla_crops_mahalla_id', 'mahalla_crops', ['mahalla_id'], unique=False)
    op.create_table('mahalla_infrastructure',
    sa.Column('infrastructure_row_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('mahalla_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('road_total_km', sa.Float(), nullable=True),
    sa.Column('road_dirt_km', sa.Float(), nullable=True),
    sa.Column('road_asphalt_km', sa.Float(), nullable=True),
    sa.Column('households_without_drinking_water_count', sa.Integer(), nullable=True),
    sa.Column('power_outage_count', sa.Integer(), nullable=True),
    sa.Column('power_outage_hours_text', sa.Text(), nullable=True),
    sa.Column('medical_facility_distance_km', sa.Float(), nullable=True),
    sa.Column('school_count', sa.Integer(), nullable=True),
    sa.Column('sports_facility_count', sa.Integer(), nullable=True),
    sa.Column('kindergarten_count', sa.Integer(), nullable=True),
    sa.Column('homestead_area_ha', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_mahalla_infrastructure_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.mahalla_id'], name=op.f('fk_mahalla_infrastructure_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('infrastructure_row_id', name=op.f('pk_mahalla_infrastructure'))
    )
    op.create_index('ix_mahalla_infrastructure_import_run_id', 'mahalla_infrastructure', ['import_run_id'], unique=False)
    op.create_index('ix_mahalla_infrastructure_mahalla_id', 'mahalla_infrastructure', ['mahalla_id'], unique=False)
    op.create_table('mahalla_peer_factors',
    sa.Column('peer_factor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('mahalla_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('factor_polarity', sa.String(length=16), nullable=False),
    sa.Column('factor_order', sa.Integer(), nullable=False),
    sa.Column('factor_key', sa.Text(), nullable=True),
    sa.Column('factor_label_cyr', sa.Text(), nullable=True),
    sa.Column('factor_unit', sa.String(length=64), nullable=True),
    sa.Column('factor_direction', sa.String(length=8), nullable=True),
    sa.Column('entity_value_num', sa.Float(), nullable=True),
    sa.Column('comparison_average_value', sa.Float(), nullable=True),
    sa.Column('peer_rank', sa.Integer(), nullable=True),
    sa.Column('peer_count', sa.Integer(), nullable=True),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.CheckConstraint("factor_polarity IN ('strength', 'weakness')", name=op.f('ck_mahalla_peer_factors_factor_polarity_allowed')),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_mahalla_peer_factors_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.mahalla_id'], name=op.f('fk_mahalla_peer_factors_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('peer_factor_id', name=op.f('pk_mahalla_peer_factors'))
    )
    op.create_index('ix_mahalla_peer_factors_factor_key', 'mahalla_peer_factors', ['factor_key'], unique=False)
    op.create_index('ix_mahalla_peer_factors_import_run_id', 'mahalla_peer_factors', ['import_run_id'], unique=False)
    op.create_index('ix_mahalla_peer_factors_mahalla_id', 'mahalla_peer_factors', ['mahalla_id'], unique=False)
    op.create_table('mahalla_specializations',
    sa.Column('specialization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('mahalla_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.Column('specialization_slot', sa.String(length=32), nullable=True),
    sa.Column('specialization_slot_label_cyr', sa.Text(), nullable=True),
    sa.Column('specialization_type_cyr', sa.Text(), nullable=True),
    sa.Column('specialization_direction_cyr', sa.Text(), nullable=True),
    sa.Column('household_count', sa.Float(), nullable=True),
    sa.Column('population_count', sa.Float(), nullable=True),
    sa.Column('share_percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_mahalla_specializations_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.mahalla_id'], name=op.f('fk_mahalla_specializations_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('specialization_id', name=op.f('pk_mahalla_specializations'))
    )
    op.create_index('ix_mahalla_specializations_import_run_id', 'mahalla_specializations', ['import_run_id'], unique=False)
    op.create_index('ix_mahalla_specializations_mahalla_id', 'mahalla_specializations', ['mahalla_id'], unique=False)
    op.create_table('mahalla_subsidy_programs',
    sa.Column('subsidy_program_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('mahalla_id', sa.BigInteger(), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('program_order', sa.Integer(), nullable=False),
    sa.Column('subsidy_program_label_cyr', sa.Text(), nullable=True),
    sa.Column('application_count', sa.Float(), nullable=True),
    sa.Column('required_amount_mln_uzs', sa.Float(), nullable=True),
    sa.Column('has_amount_source_flag', sa.Boolean(), nullable=True),
    sa.Column('subsidies_year', sa.Integer(), nullable=True),
    sa.Column('subsidies_data_date', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.import_run_id'], name=op.f('fk_mahalla_subsidy_programs_import_run_id_import_runs')),
    sa.ForeignKeyConstraint(['mahalla_id'], ['mahallas.mahalla_id'], name=op.f('fk_mahalla_subsidy_programs_mahalla_id_mahallas')),
    sa.PrimaryKeyConstraint('subsidy_program_id', name=op.f('pk_mahalla_subsidy_programs'))
    )
    op.create_index('ix_mahalla_subsidy_programs_import_run_id', 'mahalla_subsidy_programs', ['import_run_id'], unique=False)
    op.create_index('ix_mahalla_subsidy_programs_mahalla_id', 'mahalla_subsidy_programs', ['mahalla_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mahalla_subsidy_programs_mahalla_id', table_name='mahalla_subsidy_programs')
    op.drop_index('ix_mahalla_subsidy_programs_import_run_id', table_name='mahalla_subsidy_programs')
    op.drop_table('mahalla_subsidy_programs')
    op.drop_index('ix_mahalla_specializations_mahalla_id', table_name='mahalla_specializations')
    op.drop_index('ix_mahalla_specializations_import_run_id', table_name='mahalla_specializations')
    op.drop_table('mahalla_specializations')
    op.drop_index('ix_mahalla_peer_factors_mahalla_id', table_name='mahalla_peer_factors')
    op.drop_index('ix_mahalla_peer_factors_import_run_id', table_name='mahalla_peer_factors')
    op.drop_index('ix_mahalla_peer_factors_factor_key', table_name='mahalla_peer_factors')
    op.drop_table('mahalla_peer_factors')
    op.drop_index('ix_mahalla_infrastructure_mahalla_id', table_name='mahalla_infrastructure')
    op.drop_index('ix_mahalla_infrastructure_import_run_id', table_name='mahalla_infrastructure')
    op.drop_table('mahalla_infrastructure')
    op.drop_index('ix_mahalla_crops_mahalla_id', table_name='mahalla_crops')
    op.drop_index('ix_mahalla_crops_import_run_id', table_name='mahalla_crops')
    op.drop_table('mahalla_crops')
    op.drop_index('ix_mahalla_appeals_mahalla_id', table_name='mahalla_appeals')
    op.drop_index('ix_mahalla_appeals_import_run_id', table_name='mahalla_appeals')
    op.drop_table('mahalla_appeals')
    op.drop_index('ix_entity_kpis_region_id', table_name='entity_kpis')
    op.drop_index('ix_entity_kpis_mahalla_id', table_name='entity_kpis')
    op.drop_index('ix_entity_kpis_kpi_key', table_name='entity_kpis')
    op.drop_index('ix_entity_kpis_import_run_id', table_name='entity_kpis')
    op.drop_index('ix_entity_kpis_entity_level_kpi_key', table_name='entity_kpis')
    op.drop_index('ix_entity_kpis_district_id', table_name='entity_kpis')
    op.drop_table('entity_kpis')
    op.drop_index('ix_entity_ai_insights_region_id', table_name='entity_ai_insights')
    op.drop_index('ix_entity_ai_insights_mahalla_id', table_name='entity_ai_insights')
    op.drop_index('ix_entity_ai_insights_import_run_id', table_name='entity_ai_insights')
    op.drop_index('ix_entity_ai_insights_district_id', table_name='entity_ai_insights')
    op.drop_table('entity_ai_insights')
    op.drop_index('ix_district_macro_points_macro_indicator_id', table_name='district_macro_points')
    op.drop_index('ix_district_macro_points_import_run_id', table_name='district_macro_points')
    op.drop_table('district_macro_points')
    op.drop_index('ix_mahallas_region_id', table_name='mahallas')
    op.drop_index('ix_mahallas_region_code', table_name='mahallas')
    op.drop_index('ix_mahallas_mahalla_stir', table_name='mahallas')
    op.drop_index('ix_mahallas_import_run_id', table_name='mahallas')
    op.drop_index('ix_mahallas_district_id', table_name='mahallas')
    op.drop_index('ix_mahallas_district_code', table_name='mahallas')
    op.drop_table('mahallas')
    op.drop_index('ix_district_rating_histogram_import_run_id', table_name='district_rating_histogram')
    op.drop_index('ix_district_rating_histogram_district_id', table_name='district_rating_histogram')
    op.drop_table('district_rating_histogram')
    op.drop_index('ix_district_macro_indicators_indicator_key', table_name='district_macro_indicators')
    op.drop_index('ix_district_macro_indicators_import_run_id', table_name='district_macro_indicators')
    op.drop_index('ix_district_macro_indicators_district_id', table_name='district_macro_indicators')
    op.drop_table('district_macro_indicators')
    op.drop_index('ix_district_geometries_import_run_id', table_name='district_geometries')
    op.drop_index('ix_district_geometries_district_id', table_name='district_geometries')
    op.drop_table('district_geometries')
    op.drop_index('ix_region_geometries_region_id', table_name='region_geometries')
    op.drop_index('ix_region_geometries_import_run_id', table_name='region_geometries')
    op.drop_table('region_geometries')
    op.drop_index('ix_districts_region_id', table_name='districts')
    op.drop_index('ix_districts_region_code', table_name='districts')
    op.drop_index('ix_districts_import_run_id', table_name='districts')
    op.drop_index('ix_districts_district_code', table_name='districts')
    op.drop_table('districts')
    op.drop_index('ix_source_region_files_region_code_from_filename', table_name='source_region_files')
    op.drop_index('ix_source_region_files_import_run_id', table_name='source_region_files')
    op.drop_table('source_region_files')
    op.drop_index('ix_regions_region_code', table_name='regions')
    op.drop_index('ix_regions_import_run_id', table_name='regions')
    op.drop_table('regions')
    op.drop_index('ix_data_quality_issues_region_code', table_name='data_quality_issues')
    op.drop_index('ix_data_quality_issues_mahalla_stir', table_name='data_quality_issues')
    op.drop_index('ix_data_quality_issues_issue_code', table_name='data_quality_issues')
    op.drop_index('ix_data_quality_issues_import_run_id', table_name='data_quality_issues')
    op.drop_index('ix_data_quality_issues_district_code', table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
